server:
  port: 9090

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 10MB
      enabled: true
  jackson:
    time-zone: Asia/Baku
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      write-dates-as-timestamps: false
  datasource:
    name: blog_app
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: 123456789
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  properties:
    hibernate:
      format_sql: true
  application:
    name: e-commerce

  liquibase:
    enabled: false
#    changeLog: "classpath:db/migrations/my-master-change-log.yml"
#    url: jdbc:mysql://localhost:3306/ecommerce_db
#    user: root
#    password: 123456789


jwt:
  config:
    secret-key: 3m59OX5h1ZTJsXmQF36qp7URWdFXV7Pz1WOjOmo9McCLWkxLdUVpiSAN8NlbbRXBDCTBqelhXrTWnz1W1WP0aiaPik7z5oGwYLMB1th5aFQoid2Qh7sadgmErUJstUqe
    expiration-time: 86400000
file-upload:
  settings:
    upload-folder: d:/ecommercefiles/uploads/
logging:
  level:
    liquibase: INFO
#  file:
#    name: d:/ecommercefiles/logs/logFile.txt
#    path: d:/ecommercefiles/logs/

